/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nanopb.proto */

#ifndef PROTOBUF_C_nanopb_2eproto__INCLUDED
#define PROTOBUF_C_nanopb_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/descriptor.pb-c.h"

typedef struct NanoPBOptions NanoPBOptions;


/* --- enums --- */

typedef enum _FieldType {
  /*
   * Automatically decide field type, generate static field if possible.
   */
  FIELD_TYPE__FT_DEFAULT = 0,
  /*
   * Always generate a callback field.
   */
  FIELD_TYPE__FT_CALLBACK = 1,
  /*
   * Always generate a dynamically allocated field.
   */
  FIELD_TYPE__FT_POINTER = 4,
  /*
   * Generate a static field or raise an exception if not possible.
   */
  FIELD_TYPE__FT_STATIC = 2,
  /*
   * Ignore the field completely.
   */
  FIELD_TYPE__FT_IGNORE = 3,
  /*
   * Legacy option, use the separate 'fixed_length' option instead
   */
  FIELD_TYPE__FT_INLINE = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FIELD_TYPE)
} FieldType;
typedef enum _IntSize {
  /*
   * Default, 32/64bit based on type in .proto
   */
  INT_SIZE__IS_DEFAULT = 0,
  INT_SIZE__IS_8 = 8,
  INT_SIZE__IS_16 = 16,
  INT_SIZE__IS_32 = 32,
  INT_SIZE__IS_64 = 64
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INT_SIZE)
} IntSize;
typedef enum _TypenameMangling {
  /*
   * Default, no typename mangling
   */
  TYPENAME_MANGLING__M_NONE = 0,
  /*
   * Strip current package name
   */
  TYPENAME_MANGLING__M_STRIP_PACKAGE = 1,
  /*
   * Only use last path component
   */
  TYPENAME_MANGLING__M_FLATTEN = 2,
  /*
   * Replace the package name by the initials
   */
  TYPENAME_MANGLING__M_PACKAGE_INITIALS = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TYPENAME_MANGLING)
} TypenameMangling;
typedef enum _DescriptorSize {
  /*
   * Select minimal size based on field type
   */
  DESCRIPTOR_SIZE__DS_AUTO = 0,
  /*
   * 1 word; up to 15 byte fields, no arrays
   */
  DESCRIPTOR_SIZE__DS_1 = 1,
  /*
   * 2 words; up to 4095 byte fields, 4095 entry arrays
   */
  DESCRIPTOR_SIZE__DS_2 = 2,
  /*
   * 4 words; up to 2^32-1 byte fields, 2^16-1 entry arrays
   */
  DESCRIPTOR_SIZE__DS_4 = 4,
  /*
   * 8 words; up to 2^32-1 entry arrays
   */
  DESCRIPTOR_SIZE__DS_8 = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DESCRIPTOR_SIZE)
} DescriptorSize;

/* --- messages --- */

/*
 * This is the inner options message, which basically defines options for
 * a field. When it is used in message or file scope, it applies to all
 * fields.
 */
struct  NanoPBOptions
{
  ProtobufCMessage base;
  /*
   * Allocated size for 'bytes' and 'string' fields.
   * For string fields, this should include the space for null terminator.
   */
  protobuf_c_boolean has_max_size;
  int32_t max_size;
  /*
   * Maximum length for 'string' fields. Setting this is equivalent
   * to setting max_size to a value of length+1.
   */
  protobuf_c_boolean has_max_length;
  int32_t max_length;
  /*
   * Allocated number of entries in arrays ('repeated' fields)
   */
  protobuf_c_boolean has_max_count;
  int32_t max_count;
  /*
   * Size of integer fields. Can save some memory if you don't need
   * full 32 bits for the value.
   */
  protobuf_c_boolean has_int_size;
  IntSize int_size;
  /*
   * Size for enum fields. Supported by C++11 and C23 standards.
   */
  protobuf_c_boolean has_enum_intsize;
  IntSize enum_intsize;
  /*
   * Force type of field (callback or static allocation)
   */
  protobuf_c_boolean has_type;
  FieldType type;
  /*
   * Use long names for enums, i.e. EnumName_EnumValue.
   */
  protobuf_c_boolean has_long_names;
  protobuf_c_boolean long_names;
  /*
   * Add 'packed' attribute to generated structs.
   * Note: this cannot be used on CPUs that break on unaligned
   * accesses to variables.
   */
  protobuf_c_boolean has_packed_struct;
  protobuf_c_boolean packed_struct;
  /*
   * Add 'packed' attribute to generated enums.
   */
  protobuf_c_boolean has_packed_enum;
  protobuf_c_boolean packed_enum;
  /*
   * Skip this message
   */
  protobuf_c_boolean has_skip_message;
  protobuf_c_boolean skip_message;
  /*
   * Generate oneof fields as normal optional fields instead of union.
   */
  protobuf_c_boolean has_no_unions;
  protobuf_c_boolean no_unions;
  /*
   * integer type tag for a message
   */
  protobuf_c_boolean has_msgid;
  uint32_t msgid;
  /*
   * decode oneof as anonymous union
   */
  protobuf_c_boolean has_anonymous_oneof;
  protobuf_c_boolean anonymous_oneof;
  /*
   * Proto3 singular field does not generate a "has_" flag
   */
  protobuf_c_boolean has_proto3;
  protobuf_c_boolean proto3;
  /*
   * Force proto3 messages to have no "has_" flag.
   * This was default behavior until nanopb-0.4.0.
   */
  protobuf_c_boolean has_proto3_singular_msgs;
  protobuf_c_boolean proto3_singular_msgs;
  /*
   * Generate an enum->string mapping function (can take up lots of space).
   */
  protobuf_c_boolean has_enum_to_string;
  protobuf_c_boolean enum_to_string;
  /*
   * Generate validation methods for enums
   */
  protobuf_c_boolean has_enum_validate;
  protobuf_c_boolean enum_validate;
  /*
   * Generate bytes arrays with fixed length
   */
  protobuf_c_boolean has_fixed_length;
  protobuf_c_boolean fixed_length;
  /*
   * Generate repeated field with fixed count
   */
  protobuf_c_boolean has_fixed_count;
  protobuf_c_boolean fixed_count;
  /*
   * Generate message-level callback that is called before decoding submessages.
   * This can be used to set callback fields for submsgs inside oneofs.
   */
  protobuf_c_boolean has_submsg_callback;
  protobuf_c_boolean submsg_callback;
  /*
   * Shorten or remove package names from type names.
   * This option applies only on the file level.
   */
  protobuf_c_boolean has_mangle_names;
  TypenameMangling mangle_names;
  /*
   * Data type for storage associated with callback fields.
   */
  char *callback_datatype;
  /*
   * Callback function used for encoding and decoding.
   * Prior to nanopb-0.4.0, the callback was specified in per-field pb_callback_t
   * structure. This is still supported, but does not work inside e.g. oneof or pointer
   * fields. Instead, a new method allows specifying a per-message callback that
   * will be called for all callback fields in a message type.
   */
  char *callback_function;
  /*
   * Select the size of field descriptors. This option has to be defined
   * for the whole message, not per-field. Usually automatic selection is
   * ok, but if it results in compilation errors you can increase the field
   * size here.
   */
  protobuf_c_boolean has_descriptorsize;
  DescriptorSize descriptorsize;
  /*
   * Set default value for has_ fields.
   */
  protobuf_c_boolean has_default_has;
  protobuf_c_boolean default_has;
  /*
   * Extra files to include in generated `.pb.h`
   */
  size_t n_include;
  char **include;
  /*
   * Automatic includes to exclude from generated `.pb.h`
   * Same as nanopb_generator.py command line flag -x.
   */
  size_t n_exclude;
  char **exclude;
  /*
   * Package name that applies only for nanopb.
   */
  char *package;
  /*
   * Override type of the field in generated C code. Only to be used with related field types
   */
  protobuf_c_boolean has_type_override;
  Google__Protobuf__FieldDescriptorProto__Type type_override;
  /*
   * Override of the label of the field (see FieldDescriptorProto.Label). Can be used to create
   * fields which nanopb considers required in proto3, or whether nanopb treats the field as
   * optional/required/repeated.
   */
  protobuf_c_boolean has_label_override;
  Google__Protobuf__FieldDescriptorProto__Label label_override;
  /*
   * Due to historical reasons, nanopb orders fields in structs by their tag number
   * instead of the order in .proto. Set this to false to keep the .proto order.
   * The default value will probably change to false in nanopb-0.5.0.
   */
  protobuf_c_boolean has_sort_by_tag;
  protobuf_c_boolean sort_by_tag;
  /*
   * Set the FT_DEFAULT field conversion strategy.
   * A field that can become a static member of a c struct (e.g. int, bool, etc)
   * will be a a static field.
   * Fields with dynamic length are converted to either a pointer or a callback.
   */
  protobuf_c_boolean has_fallback_type;
  FieldType fallback_type;
  /*
   * Override initializer used in generated MyMessage_init_zero and MyMessage_init_default macros
   * By default decided automatically based on field default value and datatype.
   */
  char *initializer;
  /*
   * Discard unused types that are automatically generated by protoc if they are not actually
   * needed. Currently this applies to map< > types when the field is ignored by options.
   */
  protobuf_c_boolean has_discard_unused_automatic_types;
  protobuf_c_boolean discard_unused_automatic_types;
  /*
   * Discard messages and fields marked with [deprecated = true] in the proto file.
   */
  protobuf_c_boolean has_discard_deprecated;
  protobuf_c_boolean discard_deprecated;
};
extern char nano_pboptions__callback_datatype__default_value[];
extern char nano_pboptions__callback_function__default_value[];
#define NANO_PBOPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nano_pboptions__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, INT_SIZE__IS_DEFAULT, 0, INT_SIZE__IS_DEFAULT, 0, FIELD_TYPE__FT_DEFAULT, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, TYPENAME_MANGLING__M_NONE, nano_pboptions__callback_datatype__default_value, nano_pboptions__callback_function__default_value, 0, DESCRIPTOR_SIZE__DS_AUTO, 0, 0, 0,NULL, 0,NULL, NULL, 0, GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__TYPE__TYPE_DOUBLE, 0, GOOGLE__PROTOBUF__FIELD_DESCRIPTOR_PROTO__LABEL__LABEL_OPTIONAL, 0, 1, 0, FIELD_TYPE__FT_CALLBACK, NULL, 0, 1, 0, 0 }


/* NanoPBOptions methods */
void   nano_pboptions__init
                     (NanoPBOptions         *message);
size_t nano_pboptions__get_packed_size
                     (const NanoPBOptions   *message);
size_t nano_pboptions__pack
                     (const NanoPBOptions   *message,
                      uint8_t             *out);
size_t nano_pboptions__pack_to_buffer
                     (const NanoPBOptions   *message,
                      ProtobufCBuffer     *buffer);
NanoPBOptions *
       nano_pboptions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nano_pboptions__free_unpacked
                     (NanoPBOptions *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NanoPBOptions_Closure)
                 (const NanoPBOptions *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    field_type__descriptor;
extern const ProtobufCEnumDescriptor    int_size__descriptor;
extern const ProtobufCEnumDescriptor    typename_mangling__descriptor;
extern const ProtobufCEnumDescriptor    descriptor_size__descriptor;
extern const ProtobufCMessageDescriptor nano_pboptions__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_nanopb_2eproto__INCLUDED */
