/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nanopb.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "nanopb.pb-c.h"
void   nano_pboptions__init
                     (NanoPBOptions         *message)
{
  static const NanoPBOptions init_value = NANO_PBOPTIONS__INIT;
  *message = init_value;
}
size_t nano_pboptions__get_packed_size
                     (const NanoPBOptions *message)
{
  assert(message->base.descriptor == &nano_pboptions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nano_pboptions__pack
                     (const NanoPBOptions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nano_pboptions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nano_pboptions__pack_to_buffer
                     (const NanoPBOptions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nano_pboptions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NanoPBOptions *
       nano_pboptions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NanoPBOptions *)
     protobuf_c_message_unpack (&nano_pboptions__descriptor,
                                allocator, len, data);
}
void   nano_pboptions__free_unpacked
                     (NanoPBOptions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nano_pboptions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char nano_pboptions__callback_datatype__default_value[] = "pb_callback_t";
char nano_pboptions__callback_function__default_value[] = "pb_default_field_callback";
static const IntSize nano_pboptions__int_size__default_value = INT_SIZE__IS_DEFAULT;
static const IntSize nano_pboptions__enum_intsize__default_value = INT_SIZE__IS_DEFAULT;
static const FieldType nano_pboptions__type__default_value = FIELD_TYPE__FT_DEFAULT;
static const protobuf_c_boolean nano_pboptions__long_names__default_value = 1;
static const protobuf_c_boolean nano_pboptions__packed_struct__default_value = 0;
static const protobuf_c_boolean nano_pboptions__packed_enum__default_value = 0;
static const protobuf_c_boolean nano_pboptions__skip_message__default_value = 0;
static const protobuf_c_boolean nano_pboptions__no_unions__default_value = 0;
static const protobuf_c_boolean nano_pboptions__anonymous_oneof__default_value = 0;
static const protobuf_c_boolean nano_pboptions__proto3__default_value = 0;
static const protobuf_c_boolean nano_pboptions__proto3_singular_msgs__default_value = 0;
static const protobuf_c_boolean nano_pboptions__enum_to_string__default_value = 0;
static const protobuf_c_boolean nano_pboptions__enum_validate__default_value = 0;
static const protobuf_c_boolean nano_pboptions__fixed_length__default_value = 0;
static const protobuf_c_boolean nano_pboptions__fixed_count__default_value = 0;
static const protobuf_c_boolean nano_pboptions__submsg_callback__default_value = 0;
static const TypenameMangling nano_pboptions__mangle_names__default_value = TYPENAME_MANGLING__M_NONE;
static const DescriptorSize nano_pboptions__descriptorsize__default_value = DESCRIPTOR_SIZE__DS_AUTO;
static const protobuf_c_boolean nano_pboptions__default_has__default_value = 0;
static const protobuf_c_boolean nano_pboptions__sort_by_tag__default_value = 1;
static const FieldType nano_pboptions__fallback_type__default_value = FIELD_TYPE__FT_CALLBACK;
static const protobuf_c_boolean nano_pboptions__discard_unused_automatic_types__default_value = 1;
static const protobuf_c_boolean nano_pboptions__discard_deprecated__default_value = 0;
static const ProtobufCFieldDescriptor nano_pboptions__field_descriptors[35] =
{
  {
    "max_size",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NanoPBOptions, has_max_size),
    offsetof(NanoPBOptions, max_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NanoPBOptions, has_max_count),
    offsetof(NanoPBOptions, max_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_type),
    offsetof(NanoPBOptions, type),
    &field_type__descriptor,
    &nano_pboptions__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_names",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_long_names),
    offsetof(NanoPBOptions, long_names),
    NULL,
    &nano_pboptions__long_names__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packed_struct",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_packed_struct),
    offsetof(NanoPBOptions, packed_struct),
    NULL,
    &nano_pboptions__packed_struct__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skip_message",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_skip_message),
    offsetof(NanoPBOptions, skip_message),
    NULL,
    &nano_pboptions__skip_message__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_size",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_int_size),
    offsetof(NanoPBOptions, int_size),
    &int_size__descriptor,
    &nano_pboptions__int_size__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_unions",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_no_unions),
    offsetof(NanoPBOptions, no_unions),
    NULL,
    &nano_pboptions__no_unions__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgid",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NanoPBOptions, has_msgid),
    offsetof(NanoPBOptions, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packed_enum",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_packed_enum),
    offsetof(NanoPBOptions, packed_enum),
    NULL,
    &nano_pboptions__packed_enum__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "anonymous_oneof",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_anonymous_oneof),
    offsetof(NanoPBOptions, anonymous_oneof),
    NULL,
    &nano_pboptions__anonymous_oneof__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto3",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_proto3),
    offsetof(NanoPBOptions, proto3),
    NULL,
    &nano_pboptions__proto3__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enum_to_string",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_enum_to_string),
    offsetof(NanoPBOptions, enum_to_string),
    NULL,
    &nano_pboptions__enum_to_string__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_length",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NanoPBOptions, has_max_length),
    offsetof(NanoPBOptions, max_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_length",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_fixed_length),
    offsetof(NanoPBOptions, fixed_length),
    NULL,
    &nano_pboptions__fixed_length__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_count",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_fixed_count),
    offsetof(NanoPBOptions, fixed_count),
    NULL,
    &nano_pboptions__fixed_count__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mangle_names",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_mangle_names),
    offsetof(NanoPBOptions, mangle_names),
    &typename_mangling__descriptor,
    &nano_pboptions__mangle_names__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callback_datatype",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NanoPBOptions, callback_datatype),
    NULL,
    &nano_pboptions__callback_datatype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callback_function",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NanoPBOptions, callback_function),
    NULL,
    &nano_pboptions__callback_function__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "descriptorsize",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_descriptorsize),
    offsetof(NanoPBOptions, descriptorsize),
    &descriptor_size__descriptor,
    &nano_pboptions__descriptorsize__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto3_singular_msgs",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_proto3_singular_msgs),
    offsetof(NanoPBOptions, proto3_singular_msgs),
    NULL,
    &nano_pboptions__proto3_singular_msgs__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "submsg_callback",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_submsg_callback),
    offsetof(NanoPBOptions, submsg_callback),
    NULL,
    &nano_pboptions__submsg_callback__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_has",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_default_has),
    offsetof(NanoPBOptions, default_has),
    NULL,
    &nano_pboptions__default_has__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "include",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(NanoPBOptions, n_include),
    offsetof(NanoPBOptions, include),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "package",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NanoPBOptions, package),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exclude",
    26,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(NanoPBOptions, n_exclude),
    offsetof(NanoPBOptions, exclude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type_override",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_type_override),
    offsetof(NanoPBOptions, type_override),
    &google__protobuf__field_descriptor_proto__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_by_tag",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_sort_by_tag),
    offsetof(NanoPBOptions, sort_by_tag),
    NULL,
    &nano_pboptions__sort_by_tag__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fallback_type",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_fallback_type),
    offsetof(NanoPBOptions, fallback_type),
    &field_type__descriptor,
    &nano_pboptions__fallback_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initializer",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NanoPBOptions, initializer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label_override",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_label_override),
    offsetof(NanoPBOptions, label_override),
    &google__protobuf__field_descriptor_proto__label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enum_validate",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_enum_validate),
    offsetof(NanoPBOptions, enum_validate),
    NULL,
    &nano_pboptions__enum_validate__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discard_unused_automatic_types",
    33,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_discard_unused_automatic_types),
    offsetof(NanoPBOptions, discard_unused_automatic_types),
    NULL,
    &nano_pboptions__discard_unused_automatic_types__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enum_intsize",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(NanoPBOptions, has_enum_intsize),
    offsetof(NanoPBOptions, enum_intsize),
    &int_size__descriptor,
    &nano_pboptions__enum_intsize__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discard_deprecated",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(NanoPBOptions, has_discard_deprecated),
    offsetof(NanoPBOptions, discard_deprecated),
    NULL,
    &nano_pboptions__discard_deprecated__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nano_pboptions__field_indices_by_name[] = {
  10,   /* field[10] = anonymous_oneof */
  17,   /* field[17] = callback_datatype */
  18,   /* field[18] = callback_function */
  22,   /* field[22] = default_has */
  19,   /* field[19] = descriptorsize */
  34,   /* field[34] = discard_deprecated */
  32,   /* field[32] = discard_unused_automatic_types */
  33,   /* field[33] = enum_intsize */
  12,   /* field[12] = enum_to_string */
  31,   /* field[31] = enum_validate */
  25,   /* field[25] = exclude */
  28,   /* field[28] = fallback_type */
  15,   /* field[15] = fixed_count */
  14,   /* field[14] = fixed_length */
  23,   /* field[23] = include */
  29,   /* field[29] = initializer */
  6,   /* field[6] = int_size */
  30,   /* field[30] = label_override */
  3,   /* field[3] = long_names */
  16,   /* field[16] = mangle_names */
  1,   /* field[1] = max_count */
  13,   /* field[13] = max_length */
  0,   /* field[0] = max_size */
  8,   /* field[8] = msgid */
  7,   /* field[7] = no_unions */
  24,   /* field[24] = package */
  9,   /* field[9] = packed_enum */
  4,   /* field[4] = packed_struct */
  11,   /* field[11] = proto3 */
  20,   /* field[20] = proto3_singular_msgs */
  5,   /* field[5] = skip_message */
  27,   /* field[27] = sort_by_tag */
  21,   /* field[21] = submsg_callback */
  2,   /* field[2] = type */
  26,   /* field[26] = type_override */
};
static const ProtobufCIntRange nano_pboptions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 35 }
};
const ProtobufCMessageDescriptor nano_pboptions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NanoPBOptions",
  "NanoPBOptions",
  "NanoPBOptions",
  "",
  sizeof(NanoPBOptions),
  35,
  nano_pboptions__field_descriptors,
  nano_pboptions__field_indices_by_name,
  1,  nano_pboptions__number_ranges,
  (ProtobufCMessageInit) nano_pboptions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue field_type__enum_values_by_number[6] =
{
  { "FT_DEFAULT", "FIELD_TYPE__FT_DEFAULT", 0 },
  { "FT_CALLBACK", "FIELD_TYPE__FT_CALLBACK", 1 },
  { "FT_STATIC", "FIELD_TYPE__FT_STATIC", 2 },
  { "FT_IGNORE", "FIELD_TYPE__FT_IGNORE", 3 },
  { "FT_POINTER", "FIELD_TYPE__FT_POINTER", 4 },
  { "FT_INLINE", "FIELD_TYPE__FT_INLINE", 5 },
};
static const ProtobufCIntRange field_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex field_type__enum_values_by_name[6] =
{
  { "FT_CALLBACK", 1 },
  { "FT_DEFAULT", 0 },
  { "FT_IGNORE", 3 },
  { "FT_INLINE", 5 },
  { "FT_POINTER", 4 },
  { "FT_STATIC", 2 },
};
const ProtobufCEnumDescriptor field_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FieldType",
  "FieldType",
  "FieldType",
  "",
  6,
  field_type__enum_values_by_number,
  6,
  field_type__enum_values_by_name,
  1,
  field_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue int_size__enum_values_by_number[5] =
{
  { "IS_DEFAULT", "INT_SIZE__IS_DEFAULT", 0 },
  { "IS_8", "INT_SIZE__IS_8", 8 },
  { "IS_16", "INT_SIZE__IS_16", 16 },
  { "IS_32", "INT_SIZE__IS_32", 32 },
  { "IS_64", "INT_SIZE__IS_64", 64 },
};
static const ProtobufCIntRange int_size__value_ranges[] = {
{0, 0},{8, 1},{16, 2},{32, 3},{64, 4},{0, 5}
};
static const ProtobufCEnumValueIndex int_size__enum_values_by_name[5] =
{
  { "IS_16", 2 },
  { "IS_32", 3 },
  { "IS_64", 4 },
  { "IS_8", 1 },
  { "IS_DEFAULT", 0 },
};
const ProtobufCEnumDescriptor int_size__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IntSize",
  "IntSize",
  "IntSize",
  "",
  5,
  int_size__enum_values_by_number,
  5,
  int_size__enum_values_by_name,
  5,
  int_size__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue typename_mangling__enum_values_by_number[4] =
{
  { "M_NONE", "TYPENAME_MANGLING__M_NONE", 0 },
  { "M_STRIP_PACKAGE", "TYPENAME_MANGLING__M_STRIP_PACKAGE", 1 },
  { "M_FLATTEN", "TYPENAME_MANGLING__M_FLATTEN", 2 },
  { "M_PACKAGE_INITIALS", "TYPENAME_MANGLING__M_PACKAGE_INITIALS", 3 },
};
static const ProtobufCIntRange typename_mangling__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex typename_mangling__enum_values_by_name[4] =
{
  { "M_FLATTEN", 2 },
  { "M_NONE", 0 },
  { "M_PACKAGE_INITIALS", 3 },
  { "M_STRIP_PACKAGE", 1 },
};
const ProtobufCEnumDescriptor typename_mangling__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TypenameMangling",
  "TypenameMangling",
  "TypenameMangling",
  "",
  4,
  typename_mangling__enum_values_by_number,
  4,
  typename_mangling__enum_values_by_name,
  1,
  typename_mangling__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue descriptor_size__enum_values_by_number[5] =
{
  { "DS_AUTO", "DESCRIPTOR_SIZE__DS_AUTO", 0 },
  { "DS_1", "DESCRIPTOR_SIZE__DS_1", 1 },
  { "DS_2", "DESCRIPTOR_SIZE__DS_2", 2 },
  { "DS_4", "DESCRIPTOR_SIZE__DS_4", 4 },
  { "DS_8", "DESCRIPTOR_SIZE__DS_8", 8 },
};
static const ProtobufCIntRange descriptor_size__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{0, 5}
};
static const ProtobufCEnumValueIndex descriptor_size__enum_values_by_name[5] =
{
  { "DS_1", 1 },
  { "DS_2", 2 },
  { "DS_4", 3 },
  { "DS_8", 4 },
  { "DS_AUTO", 0 },
};
const ProtobufCEnumDescriptor descriptor_size__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DescriptorSize",
  "DescriptorSize",
  "DescriptorSize",
  "",
  5,
  descriptor_size__enum_values_by_number,
  5,
  descriptor_size__enum_values_by_name,
  3,
  descriptor_size__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
