/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: RFpacket.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "RFpacket.pb-c.h"
void   packet_header__init
                     (PacketHeader         *message)
{
  static const PacketHeader init_value = PACKET_HEADER__INIT;
  *message = init_value;
}
size_t packet_header__get_packed_size
                     (const PacketHeader *message)
{
  assert(message->base.descriptor == &packet_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet_header__pack
                     (const PacketHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packet_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet_header__pack_to_buffer
                     (const PacketHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packet_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PacketHeader *
       packet_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PacketHeader *)
     protobuf_c_message_unpack (&packet_header__descriptor,
                                allocator, len, data);
}
void   packet_header__free_unpacked
                     (PacketHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packet_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   antenna_data__init
                     (AntennaData         *message)
{
  static const AntennaData init_value = ANTENNA_DATA__INIT;
  *message = init_value;
}
size_t antenna_data__get_packed_size
                     (const AntennaData *message)
{
  assert(message->base.descriptor == &antenna_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t antenna_data__pack
                     (const AntennaData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &antenna_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t antenna_data__pack_to_buffer
                     (const AntennaData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &antenna_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AntennaData *
       antenna_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AntennaData *)
     protobuf_c_message_unpack (&antenna_data__descriptor,
                                allocator, len, data);
}
void   antenna_data__free_unpacked
                     (AntennaData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &antenna_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   raw_sample__init
                     (RawSample         *message)
{
  static const RawSample init_value = RAW_SAMPLE__INIT;
  *message = init_value;
}
size_t raw_sample__get_packed_size
                     (const RawSample *message)
{
  assert(message->base.descriptor == &raw_sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t raw_sample__pack
                     (const RawSample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &raw_sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t raw_sample__pack_to_buffer
                     (const RawSample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &raw_sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RawSample *
       raw_sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RawSample *)
     protobuf_c_message_unpack (&raw_sample__descriptor,
                                allocator, len, data);
}
void   raw_sample__free_unpacked
                     (RawSample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &raw_sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   filtered_state__init
                     (FilteredState         *message)
{
  static const FilteredState init_value = FILTERED_STATE__INIT;
  *message = init_value;
}
size_t filtered_state__get_packed_size
                     (const FilteredState *message)
{
  assert(message->base.descriptor == &filtered_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t filtered_state__pack
                     (const FilteredState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &filtered_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t filtered_state__pack_to_buffer
                     (const FilteredState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &filtered_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FilteredState *
       filtered_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FilteredState *)
     protobuf_c_message_unpack (&filtered_state__descriptor,
                                allocator, len, data);
}
void   filtered_state__free_unpacked
                     (FilteredState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &filtered_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   prediction__init
                     (Prediction         *message)
{
  static const Prediction init_value = PREDICTION__INIT;
  *message = init_value;
}
size_t prediction__get_packed_size
                     (const Prediction *message)
{
  assert(message->base.descriptor == &prediction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t prediction__pack
                     (const Prediction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &prediction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t prediction__pack_to_buffer
                     (const Prediction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &prediction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Prediction *
       prediction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Prediction *)
     protobuf_c_message_unpack (&prediction__descriptor,
                                allocator, len, data);
}
void   prediction__free_unpacked
                     (Prediction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &prediction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   residual__init
                     (Residual         *message)
{
  static const Residual init_value = RESIDUAL__INIT;
  *message = init_value;
}
size_t residual__get_packed_size
                     (const Residual *message)
{
  assert(message->base.descriptor == &residual__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t residual__pack
                     (const Residual *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &residual__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t residual__pack_to_buffer
                     (const Residual *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &residual__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Residual *
       residual__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Residual *)
     protobuf_c_message_unpack (&residual__descriptor,
                                allocator, len, data);
}
void   residual__free_unpacked
                     (Residual *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &residual__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   control__init
                     (Control         *message)
{
  static const Control init_value = CONTROL__INIT;
  *message = init_value;
}
size_t control__get_packed_size
                     (const Control *message)
{
  assert(message->base.descriptor == &control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t control__pack
                     (const Control *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t control__pack_to_buffer
                     (const Control *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Control *
       control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Control *)
     protobuf_c_message_unpack (&control__descriptor,
                                allocator, len, data);
}
void   control__free_unpacked
                     (Control *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   signal_packet__init
                     (SignalPacket         *message)
{
  static const SignalPacket init_value = SIGNAL_PACKET__INIT;
  *message = init_value;
}
size_t signal_packet__get_packed_size
                     (const SignalPacket *message)
{
  assert(message->base.descriptor == &signal_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t signal_packet__pack
                     (const SignalPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &signal_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t signal_packet__pack_to_buffer
                     (const SignalPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &signal_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SignalPacket *
       signal_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SignalPacket *)
     protobuf_c_message_unpack (&signal_packet__descriptor,
                                allocator, len, data);
}
void   signal_packet__free_unpacked
                     (SignalPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &signal_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor packet_header__field_descriptors[6] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, stream_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_us",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, timestamp_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_marker",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, sync_marker),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet_header__field_indices_by_name[] = {
  4,   /* field[4] = flags */
  2,   /* field[2] = sequence */
  1,   /* field[1] = stream_id */
  5,   /* field[5] = sync_marker */
  3,   /* field[3] = timestamp_us */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange packet_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor packet_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PacketHeader",
  "PacketHeader",
  "PacketHeader",
  "",
  sizeof(PacketHeader),
  6,
  packet_header__field_descriptors,
  packet_header__field_indices_by_name,
  1,  packet_header__number_ranges,
  (ProtobufCMessageInit) packet_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor antenna_data__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AntennaData, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rss",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(AntennaData, rss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tdoa",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(AntennaData, n_tdoa),
    offsetof(AntennaData, tdoa),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aoa",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(AntennaData, n_aoa),
    offsetof(AntennaData, aoa),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "units",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AntennaData, units),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned antenna_data__field_indices_by_name[] = {
  3,   /* field[3] = aoa */
  0,   /* field[0] = name */
  1,   /* field[1] = rss */
  2,   /* field[2] = tdoa */
  4,   /* field[4] = units */
};
static const ProtobufCIntRange antenna_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor antenna_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AntennaData",
  "AntennaData",
  "AntennaData",
  "",
  sizeof(AntennaData),
  5,
  antenna_data__field_descriptors,
  antenna_data__field_indices_by_name,
  1,  antenna_data__number_ranges,
  (ProtobufCMessageInit) antenna_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor raw_sample__field_descriptors[1] =
{
  {
    "antennas",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RawSample, n_antennas),
    offsetof(RawSample, antennas),
    &antenna_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned raw_sample__field_indices_by_name[] = {
  0,   /* field[0] = antennas */
};
static const ProtobufCIntRange raw_sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor raw_sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RawSample",
  "RawSample",
  "RawSample",
  "",
  sizeof(RawSample),
  1,
  raw_sample__field_descriptors,
  raw_sample__field_indices_by_name,
  1,  raw_sample__number_ranges,
  (ProtobufCMessageInit) raw_sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor filtered_state__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(FilteredState, n_x),
    offsetof(FilteredState, x),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "P_flat",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(FilteredState, n_p_flat),
    offsetof(FilteredState, p_flat),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FilteredState, model_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "param_hash",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FilteredState, param_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned filtered_state__field_indices_by_name[] = {
  1,   /* field[1] = P_flat */
  2,   /* field[2] = model_version */
  3,   /* field[3] = param_hash */
  0,   /* field[0] = x */
};
static const ProtobufCIntRange filtered_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor filtered_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FilteredState",
  "FilteredState",
  "FilteredState",
  "",
  sizeof(FilteredState),
  4,
  filtered_state__field_descriptors,
  filtered_state__field_indices_by_name,
  1,  filtered_state__number_ranges,
  (ProtobufCMessageInit) filtered_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor prediction__field_descriptors[6] =
{
  {
    "y_hat",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Prediction, n_y_hat),
    offsetof(Prediction, y_hat),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "horizon_steps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Prediction, horizon_steps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step_interval_ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Prediction, step_interval_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_lower",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Prediction, n_conf_lower),
    offsetof(Prediction, conf_lower),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_upper",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Prediction, n_conf_upper),
    offsetof(Prediction, conf_upper),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_version",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Prediction, model_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned prediction__field_indices_by_name[] = {
  3,   /* field[3] = conf_lower */
  4,   /* field[4] = conf_upper */
  1,   /* field[1] = horizon_steps */
  5,   /* field[5] = model_version */
  2,   /* field[2] = step_interval_ms */
  0,   /* field[0] = y_hat */
};
static const ProtobufCIntRange prediction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor prediction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Prediction",
  "Prediction",
  "Prediction",
  "",
  sizeof(Prediction),
  6,
  prediction__field_descriptors,
  prediction__field_indices_by_name,
  1,  prediction__number_ranges,
  (ProtobufCMessageInit) prediction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor residual__field_descriptors[3] =
{
  {
    "innovation",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Residual, n_innovation),
    offsetof(Residual, innovation),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mae",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Residual, mae),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rmse",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Residual, rmse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned residual__field_indices_by_name[] = {
  0,   /* field[0] = innovation */
  1,   /* field[1] = mae */
  2,   /* field[2] = rmse */
};
static const ProtobufCIntRange residual__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor residual__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Residual",
  "Residual",
  "Residual",
  "",
  sizeof(Residual),
  3,
  residual__field_descriptors,
  residual__field_indices_by_name,
  1,  residual__number_ranges,
  (ProtobufCMessageInit) residual__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor control__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Control, kind),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Control, new_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Control, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned control__field_indices_by_name[] = {
  0,   /* field[0] = kind */
  1,   /* field[1] = new_version */
  2,   /* field[2] = payload */
};
static const ProtobufCIntRange control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Control",
  "Control",
  "Control",
  "",
  sizeof(Control),
  3,
  control__field_descriptors,
  control__field_indices_by_name,
  1,  control__number_ranges,
  (ProtobufCMessageInit) control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor signal_packet__field_descriptors[8] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SignalPacket, header),
    &packet_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kind",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SignalPacket, kind),
    &payload_kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SignalPacket, payload_case),
    offsetof(SignalPacket, raw),
    &raw_sample__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filtered",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SignalPacket, payload_case),
    offsetof(SignalPacket, filtered),
    &filtered_state__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "predict",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SignalPacket, payload_case),
    offsetof(SignalPacket, predict),
    &prediction__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "residual",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SignalPacket, payload_case),
    offsetof(SignalPacket, residual),
    &residual__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SignalPacket, payload_case),
    offsetof(SignalPacket, control),
    &control__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc32",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignalPacket, crc32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned signal_packet__field_indices_by_name[] = {
  6,   /* field[6] = control */
  7,   /* field[7] = crc32 */
  3,   /* field[3] = filtered */
  0,   /* field[0] = header */
  1,   /* field[1] = kind */
  4,   /* field[4] = predict */
  2,   /* field[2] = raw */
  5,   /* field[5] = residual */
};
static const ProtobufCIntRange signal_packet__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 15, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor signal_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SignalPacket",
  "SignalPacket",
  "SignalPacket",
  "",
  sizeof(SignalPacket),
  8,
  signal_packet__field_descriptors,
  signal_packet__field_indices_by_name,
  2,  signal_packet__number_ranges,
  (ProtobufCMessageInit) signal_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue payload_kind__enum_values_by_number[5] =
{
  { "RAW", "PAYLOAD_KIND__RAW", 0 },
  { "FILTERED", "PAYLOAD_KIND__FILTERED", 1 },
  { "PREDICTION", "PAYLOAD_KIND__PREDICTION", 2 },
  { "RESIDUAL", "PAYLOAD_KIND__RESIDUAL", 3 },
  { "CONTROL", "PAYLOAD_KIND__CONTROL", 4 },
};
static const ProtobufCIntRange payload_kind__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex payload_kind__enum_values_by_name[5] =
{
  { "CONTROL", 4 },
  { "FILTERED", 1 },
  { "PREDICTION", 2 },
  { "RAW", 0 },
  { "RESIDUAL", 3 },
};
const ProtobufCEnumDescriptor payload_kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PayloadKind",
  "PayloadKind",
  "PayloadKind",
  "",
  5,
  payload_kind__enum_values_by_number,
  5,
  payload_kind__enum_values_by_name,
  1,
  payload_kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
