/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: RFpacket.proto */

#ifndef PROTOBUF_C_RFpacket_2eproto__INCLUDED
#define PROTOBUF_C_RFpacket_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct PacketHeader PacketHeader;
typedef struct RFPacket RFPacket;


/* --- enums --- */


/* --- messages --- */

struct  PacketHeader
{
  ProtobufCMessage base;
  uint32_t version;
  uint32_t stream_id;
  uint32_t sequence;
  uint64_t timestamp_us;
  uint32_t flags;
  ProtobufCBinaryData sync_marker;
};
#define PACKET_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&packet_header__descriptor) \
, 0, 0, 0, 0, 0, {0,NULL} }


struct  RFPacket
{
  ProtobufCMessage base;
  /*
   * Embedded header
   */
  PacketHeader *header;
  /*
   * UTF-8, e.g., "LatticeNode1"
   */
  char *node_label;
  /*
   * UTF-8, e.g., "Init OTA"
   */
  char *status_msg;
  /*
   * Raw bytes for spectrum/AOA/RSS data
   */
  ProtobufCBinaryData rf_packet;
  /*
   * Bytes for OTA blobs
   */
  ProtobufCBinaryData firmware_update;
  /*
   * Bytes for Joseph-filtered scans
   */
  ProtobufCBinaryData spectrum_bytes;
};
#define RFPACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rfpacket__descriptor) \
, NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, {0,NULL}, {0,NULL} }


/* PacketHeader methods */
void   packet_header__init
                     (PacketHeader         *message);
size_t packet_header__get_packed_size
                     (const PacketHeader   *message);
size_t packet_header__pack
                     (const PacketHeader   *message,
                      uint8_t             *out);
size_t packet_header__pack_to_buffer
                     (const PacketHeader   *message,
                      ProtobufCBuffer     *buffer);
PacketHeader *
       packet_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   packet_header__free_unpacked
                     (PacketHeader *message,
                      ProtobufCAllocator *allocator);
/* RFPacket methods */
void   rfpacket__init
                     (RFPacket         *message);
size_t rfpacket__get_packed_size
                     (const RFPacket   *message);
size_t rfpacket__pack
                     (const RFPacket   *message,
                      uint8_t             *out);
size_t rfpacket__pack_to_buffer
                     (const RFPacket   *message,
                      ProtobufCBuffer     *buffer);
RFPacket *
       rfpacket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rfpacket__free_unpacked
                     (RFPacket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PacketHeader_Closure)
                 (const PacketHeader *message,
                  void *closure_data);
typedef void (*RFPacket_Closure)
                 (const RFPacket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor packet_header__descriptor;
extern const ProtobufCMessageDescriptor rfpacket__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_RFpacket_2eproto__INCLUDED */
