// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RFpacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from RFpacket.proto</summary>
public static partial class RFpacketReflection {

  #region Descriptor
  /// <summary>File descriptor for RFpacket.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RFpacketReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5SRnBhY2tldC5wcm90byJ+CgxQYWNrZXRIZWFkZXISDwoHdmVyc2lvbhgB",
          "IAEoDRIRCglzdHJlYW1faWQYAiABKA0SEAoIc2VxdWVuY2UYAyABKA0SFAoM",
          "dGltZXN0YW1wX3VzGAQgASgEEg0KBWZsYWdzGAUgASgNEhMKC3N5bmNfbWFy",
          "a2VyGAYgASgMIpUBCghSRlBhY2tldBIdCgZoZWFkZXIYASABKAsyDS5QYWNr",
          "ZXRIZWFkZXISEgoKbm9kZV9sYWJlbBgCIAEoCRISCgpzdGF0dXNfbXNnGAMg",
          "ASgJEhEKCXJmX3BhY2tldBgEIAEoDBIXCg9maXJtd2FyZV91cGRhdGUYBSAB",
          "KAwSFgoOc3BlY3RydW1fYnl0ZXMYBiABKAxiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PacketHeader), global::PacketHeader.Parser, new[]{ "Version", "StreamId", "Sequence", "TimestampUs", "Flags", "SyncMarker" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RFPacket), global::RFPacket.Parser, new[]{ "Header", "NodeLabel", "StatusMsg", "RfPacket", "FirmwareUpdate", "SpectrumBytes" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PacketHeader : pb::IMessage<PacketHeader>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PacketHeader> _parser = new pb::MessageParser<PacketHeader>(() => new PacketHeader());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PacketHeader> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RFpacketReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PacketHeader() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PacketHeader(PacketHeader other) : this() {
    version_ = other.version_;
    streamId_ = other.streamId_;
    sequence_ = other.sequence_;
    timestampUs_ = other.timestampUs_;
    flags_ = other.flags_;
    syncMarker_ = other.syncMarker_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PacketHeader Clone() {
    return new PacketHeader(this);
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 1;
  private uint version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Version {
    get { return version_; }
    set {
      version_ = value;
    }
  }

  /// <summary>Field number for the "stream_id" field.</summary>
  public const int StreamIdFieldNumber = 2;
  private uint streamId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StreamId {
    get { return streamId_; }
    set {
      streamId_ = value;
    }
  }

  /// <summary>Field number for the "sequence" field.</summary>
  public const int SequenceFieldNumber = 3;
  private uint sequence_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Sequence {
    get { return sequence_; }
    set {
      sequence_ = value;
    }
  }

  /// <summary>Field number for the "timestamp_us" field.</summary>
  public const int TimestampUsFieldNumber = 4;
  private ulong timestampUs_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong TimestampUs {
    get { return timestampUs_; }
    set {
      timestampUs_ = value;
    }
  }

  /// <summary>Field number for the "flags" field.</summary>
  public const int FlagsFieldNumber = 5;
  private uint flags_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Flags {
    get { return flags_; }
    set {
      flags_ = value;
    }
  }

  /// <summary>Field number for the "sync_marker" field.</summary>
  public const int SyncMarkerFieldNumber = 6;
  private pb::ByteString syncMarker_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString SyncMarker {
    get { return syncMarker_; }
    set {
      syncMarker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PacketHeader);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PacketHeader other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Version != other.Version) return false;
    if (StreamId != other.StreamId) return false;
    if (Sequence != other.Sequence) return false;
    if (TimestampUs != other.TimestampUs) return false;
    if (Flags != other.Flags) return false;
    if (SyncMarker != other.SyncMarker) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Version != 0) hash ^= Version.GetHashCode();
    if (StreamId != 0) hash ^= StreamId.GetHashCode();
    if (Sequence != 0) hash ^= Sequence.GetHashCode();
    if (TimestampUs != 0UL) hash ^= TimestampUs.GetHashCode();
    if (Flags != 0) hash ^= Flags.GetHashCode();
    if (SyncMarker.Length != 0) hash ^= SyncMarker.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Version != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    if (StreamId != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(StreamId);
    }
    if (Sequence != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Sequence);
    }
    if (TimestampUs != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(TimestampUs);
    }
    if (Flags != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(Flags);
    }
    if (SyncMarker.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(SyncMarker);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Version != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    if (StreamId != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(StreamId);
    }
    if (Sequence != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Sequence);
    }
    if (TimestampUs != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(TimestampUs);
    }
    if (Flags != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(Flags);
    }
    if (SyncMarker.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(SyncMarker);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Version != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
    }
    if (StreamId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StreamId);
    }
    if (Sequence != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sequence);
    }
    if (TimestampUs != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampUs);
    }
    if (Flags != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Flags);
    }
    if (SyncMarker.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(SyncMarker);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PacketHeader other) {
    if (other == null) {
      return;
    }
    if (other.Version != 0) {
      Version = other.Version;
    }
    if (other.StreamId != 0) {
      StreamId = other.StreamId;
    }
    if (other.Sequence != 0) {
      Sequence = other.Sequence;
    }
    if (other.TimestampUs != 0UL) {
      TimestampUs = other.TimestampUs;
    }
    if (other.Flags != 0) {
      Flags = other.Flags;
    }
    if (other.SyncMarker.Length != 0) {
      SyncMarker = other.SyncMarker;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 16: {
          StreamId = input.ReadUInt32();
          break;
        }
        case 24: {
          Sequence = input.ReadUInt32();
          break;
        }
        case 32: {
          TimestampUs = input.ReadUInt64();
          break;
        }
        case 40: {
          Flags = input.ReadUInt32();
          break;
        }
        case 50: {
          SyncMarker = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 16: {
          StreamId = input.ReadUInt32();
          break;
        }
        case 24: {
          Sequence = input.ReadUInt32();
          break;
        }
        case 32: {
          TimestampUs = input.ReadUInt64();
          break;
        }
        case 40: {
          Flags = input.ReadUInt32();
          break;
        }
        case 50: {
          SyncMarker = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Wrapper for full packet
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RFPacket : pb::IMessage<RFPacket>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RFPacket> _parser = new pb::MessageParser<RFPacket>(() => new RFPacket());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RFPacket> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RFpacketReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RFPacket() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RFPacket(RFPacket other) : this() {
    header_ = other.header_ != null ? other.header_.Clone() : null;
    nodeLabel_ = other.nodeLabel_;
    statusMsg_ = other.statusMsg_;
    rfPacket_ = other.rfPacket_;
    firmwareUpdate_ = other.firmwareUpdate_;
    spectrumBytes_ = other.spectrumBytes_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RFPacket Clone() {
    return new RFPacket(this);
  }

  /// <summary>Field number for the "header" field.</summary>
  public const int HeaderFieldNumber = 1;
  private global::PacketHeader header_;
  /// <summary>
  /// Embedded header
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PacketHeader Header {
    get { return header_; }
    set {
      header_ = value;
    }
  }

  /// <summary>Field number for the "node_label" field.</summary>
  public const int NodeLabelFieldNumber = 2;
  private string nodeLabel_ = "";
  /// <summary>
  /// UTF-8, e.g., "LatticeNode1"
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NodeLabel {
    get { return nodeLabel_; }
    set {
      nodeLabel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "status_msg" field.</summary>
  public const int StatusMsgFieldNumber = 3;
  private string statusMsg_ = "";
  /// <summary>
  /// UTF-8, e.g., "Init OTA"
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string StatusMsg {
    get { return statusMsg_; }
    set {
      statusMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "rf_packet" field.</summary>
  public const int RfPacketFieldNumber = 4;
  private pb::ByteString rfPacket_ = pb::ByteString.Empty;
  /// <summary>
  /// Raw bytes for spectrum/AOA/RSS data
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString RfPacket {
    get { return rfPacket_; }
    set {
      rfPacket_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "firmware_update" field.</summary>
  public const int FirmwareUpdateFieldNumber = 5;
  private pb::ByteString firmwareUpdate_ = pb::ByteString.Empty;
  /// <summary>
  /// Bytes for OTA blobs
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString FirmwareUpdate {
    get { return firmwareUpdate_; }
    set {
      firmwareUpdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "spectrum_bytes" field.</summary>
  public const int SpectrumBytesFieldNumber = 6;
  private pb::ByteString spectrumBytes_ = pb::ByteString.Empty;
  /// <summary>
  /// Bytes for Joseph-filtered scans
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString SpectrumBytes {
    get { return spectrumBytes_; }
    set {
      spectrumBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RFPacket);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RFPacket other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Header, other.Header)) return false;
    if (NodeLabel != other.NodeLabel) return false;
    if (StatusMsg != other.StatusMsg) return false;
    if (RfPacket != other.RfPacket) return false;
    if (FirmwareUpdate != other.FirmwareUpdate) return false;
    if (SpectrumBytes != other.SpectrumBytes) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (header_ != null) hash ^= Header.GetHashCode();
    if (NodeLabel.Length != 0) hash ^= NodeLabel.GetHashCode();
    if (StatusMsg.Length != 0) hash ^= StatusMsg.GetHashCode();
    if (RfPacket.Length != 0) hash ^= RfPacket.GetHashCode();
    if (FirmwareUpdate.Length != 0) hash ^= FirmwareUpdate.GetHashCode();
    if (SpectrumBytes.Length != 0) hash ^= SpectrumBytes.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (header_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Header);
    }
    if (NodeLabel.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(NodeLabel);
    }
    if (StatusMsg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(StatusMsg);
    }
    if (RfPacket.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(RfPacket);
    }
    if (FirmwareUpdate.Length != 0) {
      output.WriteRawTag(42);
      output.WriteBytes(FirmwareUpdate);
    }
    if (SpectrumBytes.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(SpectrumBytes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (header_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Header);
    }
    if (NodeLabel.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(NodeLabel);
    }
    if (StatusMsg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(StatusMsg);
    }
    if (RfPacket.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(RfPacket);
    }
    if (FirmwareUpdate.Length != 0) {
      output.WriteRawTag(42);
      output.WriteBytes(FirmwareUpdate);
    }
    if (SpectrumBytes.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(SpectrumBytes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (header_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
    }
    if (NodeLabel.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NodeLabel);
    }
    if (StatusMsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(StatusMsg);
    }
    if (RfPacket.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(RfPacket);
    }
    if (FirmwareUpdate.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(FirmwareUpdate);
    }
    if (SpectrumBytes.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(SpectrumBytes);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RFPacket other) {
    if (other == null) {
      return;
    }
    if (other.header_ != null) {
      if (header_ == null) {
        Header = new global::PacketHeader();
      }
      Header.MergeFrom(other.Header);
    }
    if (other.NodeLabel.Length != 0) {
      NodeLabel = other.NodeLabel;
    }
    if (other.StatusMsg.Length != 0) {
      StatusMsg = other.StatusMsg;
    }
    if (other.RfPacket.Length != 0) {
      RfPacket = other.RfPacket;
    }
    if (other.FirmwareUpdate.Length != 0) {
      FirmwareUpdate = other.FirmwareUpdate;
    }
    if (other.SpectrumBytes.Length != 0) {
      SpectrumBytes = other.SpectrumBytes;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (header_ == null) {
            Header = new global::PacketHeader();
          }
          input.ReadMessage(Header);
          break;
        }
        case 18: {
          NodeLabel = input.ReadString();
          break;
        }
        case 26: {
          StatusMsg = input.ReadString();
          break;
        }
        case 34: {
          RfPacket = input.ReadBytes();
          break;
        }
        case 42: {
          FirmwareUpdate = input.ReadBytes();
          break;
        }
        case 50: {
          SpectrumBytes = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (header_ == null) {
            Header = new global::PacketHeader();
          }
          input.ReadMessage(Header);
          break;
        }
        case 18: {
          NodeLabel = input.ReadString();
          break;
        }
        case 26: {
          StatusMsg = input.ReadString();
          break;
        }
        case 34: {
          RfPacket = input.ReadBytes();
          break;
        }
        case 42: {
          FirmwareUpdate = input.ReadBytes();
          break;
        }
        case 50: {
          SpectrumBytes = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
