/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: RFpacket.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "RFpacket.pb-c.h"
void   packet_header__init
                     (PacketHeader         *message)
{
  static const PacketHeader init_value = PACKET_HEADER__INIT;
  *message = init_value;
}
size_t packet_header__get_packed_size
                     (const PacketHeader *message)
{
  assert(message->base.descriptor == &packet_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet_header__pack
                     (const PacketHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packet_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet_header__pack_to_buffer
                     (const PacketHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packet_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PacketHeader *
       packet_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PacketHeader *)
     protobuf_c_message_unpack (&packet_header__descriptor,
                                allocator, len, data);
}
void   packet_header__free_unpacked
                     (PacketHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packet_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rfpacket__init
                     (RFPacket         *message)
{
  static const RFPacket init_value = RFPACKET__INIT;
  *message = init_value;
}
size_t rfpacket__get_packed_size
                     (const RFPacket *message)
{
  assert(message->base.descriptor == &rfpacket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rfpacket__pack
                     (const RFPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rfpacket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rfpacket__pack_to_buffer
                     (const RFPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rfpacket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RFPacket *
       rfpacket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RFPacket *)
     protobuf_c_message_unpack (&rfpacket__descriptor,
                                allocator, len, data);
}
void   rfpacket__free_unpacked
                     (RFPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rfpacket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor packet_header__field_descriptors[6] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, stream_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_us",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, timestamp_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_marker",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PacketHeader, sync_marker),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet_header__field_indices_by_name[] = {
  4,   /* field[4] = flags */
  2,   /* field[2] = sequence */
  1,   /* field[1] = stream_id */
  5,   /* field[5] = sync_marker */
  3,   /* field[3] = timestamp_us */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange packet_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor packet_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PacketHeader",
  "PacketHeader",
  "PacketHeader",
  "",
  sizeof(PacketHeader),
  6,
  packet_header__field_descriptors,
  packet_header__field_indices_by_name,
  1,  packet_header__number_ranges,
  (ProtobufCMessageInit) packet_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rfpacket__field_descriptors[6] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RFPacket, header),
    &packet_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_label",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RFPacket, node_label),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status_msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RFPacket, status_msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rf_packet",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RFPacket, rf_packet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_update",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RFPacket, firmware_update),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spectrum_bytes",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RFPacket, spectrum_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rfpacket__field_indices_by_name[] = {
  4,   /* field[4] = firmware_update */
  0,   /* field[0] = header */
  1,   /* field[1] = node_label */
  3,   /* field[3] = rf_packet */
  5,   /* field[5] = spectrum_bytes */
  2,   /* field[2] = status_msg */
};
static const ProtobufCIntRange rfpacket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rfpacket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RFPacket",
  "RFPacket",
  "RFPacket",
  "",
  sizeof(RFPacket),
  6,
  rfpacket__field_descriptors,
  rfpacket__field_indices_by_name,
  1,  rfpacket__number_ranges,
  (ProtobufCMessageInit) rfpacket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
